### ISSUE TITLE
Issue/Request

### ISSUE THREAD

**Issue by cooldude121212** [WeatherElectric/Lacrimosum#1]
Mod is looking good so far but...
The bubble on head clips the camera A LOT
and an option to turn off the dude on the title screen would be nice

**Comment by FragileDeviations** [comment]
The bubble should already be fixed in v1.0.2, thunderstore's just really late.

**Comment by FragileDeviations** [comment]
Ah nope, I see what you mean. Will be fixed.

**Comment by FragileDeviations** [comment]
Fixed in v1.0.3
