### ISSUE TITLE
Mod breaks shovels after a snare flea jumps on your head

### ISSUE THREAD

**Issue by Lunxara** [WeatherElectric/Lacrimosum#2]
So it seems your mod patches shovels which it shouldn't be doing, and in turn causes shovels to break when a snare flea latches onto you. This can be resolved if you use the vanilla code instead.

[20:58:47.0359016] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Lacrimosum.Patching.WeaponEventTracker.OnShovelHit (On.Shovel+orig_HitShovel orig, Shovel self, System.Boolean cancel) (at <85bd20e9f37241d7a7d1153ab1229a28>:IL_0000)
DMD<>?1032001170.Hook<Shovel::HitShovel>?-1296047576 (Shovel , System.Boolean ) (at <1d0a9b25a52e4e0b93ceaa270189e3e6>:IL_0015)
Shovel+<reelUpShovel>d__14.MoveNext () (at <066a7b7eb8c24d4facd1e255e669803f>:IL_0120)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[20:58:47.0439443] [Error  :UnityDebuggerAssistant] 

--- Exception Handler ---

Exception Caught: System.NullReferenceException
Assembly: Lacrimosum

  Plugin Info
    GUID:     fragiledeviations.lacrimosum
    NAME/VER: Lacrimosum@1.2.0
    LOCATION: \plugins\FragileDeviations-Lacrimosum\Lacrimosum.dll

Message: Object reference not set to an instance of an object
Source: Lacrimosum

  --- Begin Frames ---

  --FRAME 1:
    In Assembly: Lacrimosum
    Target Method: WeaponEventTracker.OnShovelHit

  --FRAME 2:
    In Assembly: DMDASM.B0F4225E.MethodBuilder
    Target Method: DMD<>?1032001170.Hook<Shovel::HitShovel>?-1296047576

  --FRAME 3:
    In Assembly: Assembly-CSharp
    Target Method: <reelUpShovel>d__14.MoveNext

  --FRAME 4:
    In Assembly: UnityEngine.CoreModule
    Target Method: SetupCoroutine.InvokeMoveNext

  --- End Frames ---

--- End Exception Handler ---

**Comment by FragileDeviations** [comment]
There's no override for hit, forcing me to have to patch shovel hit.

**Comment by FragileDeviations** [comment]
Fixed in v1.3.1, just took the shovel's direct code for the ukulele script

**Comment by Lunxara** [comment]
> Fixed in v1.3.1, just took the shovel's direct code for the ukulele script

Yay :D I'm glad it worked
