### ISSUE TITLE
[Suggestion] Add a config option to disable the store items

### ISSUE THREAD

**Issue by Lunxara** [WeatherElectric/Lacrimosum#3]
Hey I would love an option to disable the store items if you're okay with adding a bool toggle for that, I want the mod purely for the scrap additions cus they're fun :D

**Comment by FragileDeviations** [comment]
Yeah I could do that in the next update, I was thinking of doing that actually

**Comment by Lunxara** [comment]
> Yeah I could do that in the next update, I was thinking of doing that actually

Perfect <3 ty ^^

**Comment by FragileDeviations** [comment]
Added in v1.4.0
