### ISSUE TITLE
[BUG] Permanent Effects

### ISSUE THREAD

**Issue by PenguCCN** [WeatherElectric/Lacrimosum#7]
**Describe The Bug**
Compatibility issue with Ship Inventory. Placing an item that directly affects character status into the ship inventory causes the player to be permanently affected until it's removal.

**To Reproduce**
1. Get speed or healing item.
2. Place into ship inventory chute.
3. See Error

**Comment by FragileDeviations** [comment]
Then the ship inventory mod is not properly removing the item from the player's inventory. Which would mean you should ask them to fix it, I don't develop that mod and that error is caused by an item not properly being disposed, so Ship Inventory does not properly interact with scrap.
